#!/usr/bin/env bash

# Offer to install tmux if missing.
if ! command -v tmux &> /dev/null; then
    echo "tmux is not installed. Would you like to install it? (y/n)"
    read -r response
    if [[ "$response" =~ ^[Yy]$ ]]; then
        if command -v brew &> /dev/null; then
            brew install tmux
        else
            echo "Package manager not detected. Please install tmux manually."
            exit 1
        fi
    else
        echo "Meh, no tmux. Call 'pwi' for just the REPL then or dunno..."
        exit 1
    fi
fi


case $1 in
    "") pw attach || pw ss ;;
    "attach") tmux attach -t pw 2>/dev/null ;;
    "ss") tmux new-session -d -s pw "pwi" ;;
    "cmd")
        LOGFILE=~/.tmux/pw.log
        tmux pipe-pane -t pw "cat > $LOGFILE"
        timeout 30 sed '/<<</q' <(tail -n0 -f $LOGFILE ) &
        sed_pid=$!
        tmux send-keys -t pw "$2" Enter
        wait $sed_pid
    ;;
    "read") tmux capture-pane -t pw -p -S-${2:-30} ;;
    "end") tmux kill-session -t pw ;;
    "claude") cp -i ./pw.md ~/.claude/commands ;; # Add/sync Claude command. NOTE: Only works from project dir.
    "learn") pwi learn ;;
    *) pw cmd "$@" ;;
esac
